version: "3"

services:

  gateway:
    image: "dockersetup_gateway"
    ports:
      - "8000:80"
      - "80:80"
    networks:
      - frontend
    depends_on:
      - "api"
      - "webapp"

  redis:
    image: "redis"
    networks:
      - frontend
      - backend
    depends_on:
      - "gateway"
      - "webapp"      

  webapp:
    image: "dockersetup_webapp"
    ports: 
      - 8001:80
      - 8003:443    
    environment:
      - no_proxy=api,stock,purchase,sale,quotation,company,bill
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/erp:/home/www-data/web2py/applications/erp
    links:
      - mysqldb
      - api
    depends_on:
      - "api"
      - "mysqldb"
    deploy:
      replicas: 3
   
  api:  
    image: "dockersetup_api"
    ports: 
      - 8002:80
      - 8004:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"

  stock:
    image: "dockersetup_stock"   
    ports: 
      - 8006:80
      - 8007:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"

  company:
    image: "dockersetup_company"
    ports: 
      - 8008:80
      - 8009:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"
  
  purchase:
    image: "dockersetup_purchase"
    ports: 
      - 8010:80
      - 8011:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"

  sale:
    image: "dockersetup_sale"
    ports: 
      - 8012:80
      - 8013:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"

  quotation:
    image: "dockersetup_quotation"
    ports: 
      - 8014:80
      - 8015:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"

  bill:
    image: "dockersetup_bill"    
    ports: 
      - 8016:80
      - 8017:443 
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/web2py/applications/api:/home/www-data/web2py/applications/api
    links:
      - mysqldb
    depends_on:
      - "mysqldb"

  mysqldb:
    image: "dockersetup_mysqldb"
    ports:
      - "3306:3306"
    volumes:
      - /home/adityagaykar/dev/mysqldata:/var/lib/mysql
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - gateway
      - controller
      - mysql-db
      - frontend
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
    #driver: overlay
  backend:
    #driver: overlay
